import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import './globals.css';
// KaTeX 0.16.11 CSS — the exam question/option HTML from the API contains
// pre-rendered KaTeX markup (generated by the admin Quill editor, same version).
// Without this stylesheet the MathML fallback leaks as duplicate text and the
// sqrt renders as a stretched line. Bundled from node_modules → served same-origin.
import 'katex/dist/katex.min.css';
import SessionProvider from '@/components/providers/SessionProvider';

const inter = Inter({
  subsets: ['latin', 'latin-ext'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  // (base URL for all SEO)
  metadataBase: new URL('https://www.gridacademy.in'),

  title: {
    default: "GridAcademy — India's Best Mock Test Platform",
    template: '%s | GridAcademy',
  },

  description:
    'Prepare for SSC, Banking, Railway, UPSC and more with expert-created mock tests from top coaching institutes.',

  keywords: [
    'mock test',
    'SSC CGL',
    'IBPS PO',
    'RRB NTPC',
    'UPSC',
    'competitive exam preparation India',
  ],

  icons: {
    icon: '/favicon.svg',
    shortcut: '/favicon.svg',
    apple: '/favicon.svg',
  },

  alternates: {
    canonical: '/',
  },

  // OPEN GRAPH (Fixed with metadataBase support)
  openGraph: {
    title: "GridAcademy — India's Best Mock Test Platform",
    description:
      'Prepare for SSC, Banking, Railway, UPSC and more with expert-created mock tests.',
    url: '/',
    siteName: 'GridAcademy',
    images: [
      {
        url: '/og-image.jpg', // metadataBase automatically prefix karega
        width: 1200,
        height: 630,
      },
    ],
    locale: 'en_IN',
    type: 'website',
  },

  
  twitter: {
    card: 'summary_large_image',
    title: "GridAcademy — India's Best Mock Test Platform",
    description:
      'Prepare for SSC, Banking, Railway, UPSC and more with expert mock tests.',
    images: ['/og-image.jpg'],
  },

  
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
        <link rel="sitemap" type="application/xml" href="/sitemap.xml" />
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />

        {/* Organization structured data for AI search and brand recognition */}
        <Script id="schema-organization" type="application/ld+json" strategy="beforeInteractive">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Organization",
            "name": "GridAcademy",
            "url": "https://www.gridacademy.in",
            "logo": "https://www.gridacademy.in/logo.png",
            "description": "GridAcademy is India's trusted marketplace for competitive exam mock tests. We partner with 100+ coaching institutes to provide 1,200+ free and paid mock tests for SSC, Banking, Railway, UPSC, CUET, NEET, Defence, and State PSC exams.",
            "sameAs": [
              "https://www.instagram.com/gridacademy.in/"
            ],
            "contactPoint": {
              "@type": "ContactPoint",
              "email": "info@gridacademy.in",
              "contactType": "customer support",
              "availableLanguage": ["English", "Hindi"],
              "areaServed": "IN"
            },
            "knowsAbout": [
              "SSC CGL Mock Tests",
              "IBPS PO Preparation",
              "RRB NTPC Practice Papers",
              "UPSC Prelims Test Series",
              "CUET UG Mock Tests",
              "NEET Mock Tests",
              "Competitive Exam Preparation India"
            ],
            "areaServed": "IN",
            "foundingDate": "2023"
          })}
        </Script>

        {/* WebSite structured data with SearchAction for sitelinks searchbox */}
        <Script id="schema-website" type="application/ld+json" strategy="beforeInteractive">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebSite",
            "name": "GridAcademy",
            "url": "https://www.gridacademy.in",
            "description": "India's trusted marketplace for competitive exam mock tests.",
            "publisher": {
              "@type": "Organization",
              "name": "GridAcademy",
              "url": "https://www.gridacademy.in"
            },
            "potentialAction": {
              "@type": "SearchAction",
              "target": {
                "@type": "EntryPoint",
                "urlTemplate": "https://www.gridacademy.in/exams?q={search_term_string}"
              },
              "query-input": "required name=search_term_string"
            },
            "inLanguage": "en-IN"
          })}
        </Script>

        {/* Speakable specification for voice search optimization */}
        <Script id="schema-speakable" type="application/ld+json" strategy="beforeInteractive">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebPage",
            "speakable": {
              "@type": "SpeakableSpecification",
              "cssSelector": [
                ".exam-hero-title",
                ".key-facts",
                ".faq-question",
                ".article-heading"
              ]
            }
          })}
        </Script>

        {/* ✅ Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-Z3KQZWY3X6"
          strategy="beforeInteractive"
        />
        <Script id="google-analytics" strategy="beforeInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-Z3KQZWY3X6', {
              page_path: window.location.pathname,
            });
          `}
        </Script>
      </head>

      <body className="font-sans antialiased bg-gray-50">
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}